# config/packages/mailer.yaml
framework:
    mailer:
        # dsn: '%env(MAILER_DSN)%'
        dsn: 'gmail+smtp://rayan.lahmar@esprit.tn:201JMT3276@default'
        message_bus:  false
#  mailer:
#     dsn: 'gmail+smtp://emna.abbessi@esprit.tn:12715163@default'
#     message_bus: false


    
    #   dsn: 'gmail+smtp://maram.brinsi@esprit.tn:98568813@default'
    #   message_bus: false
