#index:
#    path: /
#    controller: App\Controller\DefaultController::index
email1:
    path: /email1
    controller: App\Controller\EmailController::sendEmail
gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcb