# config/routes.yaml

app_products:
    path: /Produit/afficher
    controller: App\Controller\ProduitController::affiche1

# search:
#   path: /search
#   controller: App\Controller\Coaching::afficherback



email1:
    path: /email1
    controller: App\Controller\EmailController::sendEmail
gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcb
2fa_login:
    path: /2fa
    controller: "scheb_two_factor.form_controller::form"

2fa_login_check:
    path: /2fa_check

not_found:
    path: '{any}'
    requirements:
        any: '.+'
    controller: App\Controller\ExceptionController::notFound